---
title: "animations"
author: "Noah Weidig"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE)
rm(list = ls())
if (!require("pacman")) install.packages("pacman")
pacman::p_load(readxl, scales, tidyverse, gganimate)
```

```{r fires}
fires <- read_excel("fires.xlsx") %>%
  mutate(Ig_Date    =  as_date(Ig_Date),
         year       =  as.numeric(year(as_date(Ig_Date)))) %>%
  filter(area_ha    >  200, Incid_Type == "Wildfire",
         year       >= 1986 & year       <= 2021) %>%
  subset(select = c("STATE_NAME", "L3_KEY", "year",
                    "WUIFLAG1990", "WUIFLAG2000",
                    "WUIFLAG2010", "WUIFLAG2020",
                    "WUICLASS1990", "WUICLASS2000",
                    "WUICLASS2010", "WUICLASS2020",
                    "Event_ID", "Ig_Date", "area_ha", "Shape_Area")) %>%
  mutate(wui_status = case_when(((year %in% 1986:1995 & WUIFLAG1990 != 0) |
                                 (year %in% 1996:2005 & WUIFLAG2000 != 0) |
                                 (year %in% 2006:2015 & WUIFLAG2010 != 0) |
                                 (year %in% 2016:2021 & WUIFLAG2020 != 0)) ~ "wui",
                                TRUE ~ "non_wui")) %>%
  group_by(Event_ID) %>%
  mutate(wui_status = if(any(wui_status == "wui")) "wui" else "non_wui")

L3_KEY <- c("08  Eastern Temperate Forests")

fires_l1_sum <- fires %>%
  group_by(wui_status) %>%
  summarize(count         = n_distinct(Event_ID),
            ha_burned     = round(sum(Shape_Area/10000), 0),
            avg_size      = round(mean(unique(area_ha)), 0),
            size_se       = round(sqrt(var(unique(area_ha)) /
                                         length(unique(area_ha))), 0)) %>%
  ungroup() %>%
  pivot_wider(names_from  = wui_status,
              values_from = c(count, avg_size,
                              size_se, ha_burned)) %>%
  mutate(across(contains(c("count", "burned")), ~ replace(., is.na(.), 0))) %>%
  unite(., col = "avg_size_wui", avg_size_wui, size_se_wui,
        na.rm = TRUE, sep = " ± ") %>%
  unite(., col = "avg_size_non_wui", avg_size_non_wui, size_se_non_wui,
        na.rm = TRUE, sep = " ± ") %>%
  cbind(L3_KEY, .)

fires_l3_sum <- fires %>%
  group_by(L3_KEY, wui_status) %>%
  summarize(count         = n_distinct(Event_ID),
            ha_burned     = round(sum(Shape_Area/10000), 0),
            avg_size      = round(mean(unique(area_ha)), 0),
            size_se       = round(sqrt(var(unique(area_ha)) /
                                         length(unique(area_ha))), 0)) %>%
  ungroup() %>%
  pivot_wider(names_from  = wui_status,
              values_from = c(count, avg_size,
                              size_se, ha_burned)) %>%
  mutate(across(contains(c("count", "burned")), ~ replace(., is.na(.), 0))) %>%
  unite(., col = "avg_size_wui",     avg_size_wui,     size_se_wui,
        na.rm = TRUE, sep = " ± ") %>%
  unite(., col = "avg_size_non_wui", avg_size_non_wui, size_se_non_wui,
        na.rm = TRUE, sep = " ± ")
```

```{r season}
l1_season <- fires %>%
  mutate(year_day = make_date(2020, 1, 1) + days(yday(Ig_Date) - 1),  
         decade = case_when(year >= 1986 & year <= 1997 ~ "1986-1997",
                            year >= 1998 & year <= 2009 ~ "1998-2009",
                            year >= 2010 & year <= 2021 ~ "2010-2021")) %>%
  distinct(Event_ID, L3_KEY, .keep_all = TRUE)

p <- l1_season %>%
  ggplot(data = .,
       mapping = aes(x = year_day, fill = wui_status)) +
  geom_density(alpha = 0.4, aes(color = wui_status, fill = wui_status), linewidth = 2.4) +
  theme_bw() +
  theme(legend.position  = "bottom",
        legend.spacing.x = unit(2, 'cm'),
        legend.spacing.y = unit(2, 'cm'),
        legend.key.size  = unit(1.75, 'cm'),
        legend.title     = element_blank(),
        legend.text      = element_text(size = 30, color = "black"),
        axis.title       = element_text(size = 30, color = "black", face = "bold"),
        axis.text        = element_text(size = 30, color = "black", ),
        panel.grid.minor = element_blank(),
        panel.border     = element_blank(),
        axis.line        = element_line(linewidth = 1.5),
        plot.title       = element_text(size = 50)) +
  scale_x_date(date_breaks = "90 days", labels = date_format("%b"),
               limits = as.Date(c('2020-01-01', '2020-12-31')), expand = c(0.05, 0.05)) +
  scale_fill_manual(values  = c("#0072B240", "#D55E0040"), labels = c("non-WUI", "WUI")) +
  scale_color_manual(values = c("#0072B2",   "#D55E00"),   labels = c("non-WUI", "WUI")) +
  labs(x = "", y = "Fire Density", title = "{closest_state}") +
  transition_states(decade, transition_length = 2, state_length = 1)

animate(p, height = 800, width = 1400)

anim_save("seasonality.gif")
```

```{r l1_sum_density}
p <- l1_season %>%
  ggplot(data = .,
       mapping = aes(x = year_day, fill = wui_status)) +
  geom_density(alpha = 0.4, aes(color = wui_status, fill = wui_status), linewidth = 2.4) +
  theme_bw() +
  theme(legend.position  = "bottom",
        legend.spacing.x = unit(2, 'cm'),
        legend.spacing.y = unit(2, 'cm'),
        legend.key.size  = unit(1.75, 'cm'),
        legend.title     = element_blank(),
        legend.text      = element_text(size = 30, color = "black"),
        axis.title       = element_text(size = 30, color = "black", face = "bold"),
        axis.text        = element_text(size = 30, color = "black", ),
        panel.grid.minor = element_blank(),
        panel.border     = element_blank(),
        axis.line        = element_line(linewidth = 1.5),
        plot.title       = element_text(size = 50)) +
  scale_x_date(date_breaks = "90 days", labels = date_format("%b"),
               limits = as.Date(c('2020-01-01', '2020-12-31')), expand = c(0.05, 0.05)) +
  scale_fill_manual(values  = c("#0072B240", "#D55E0040"), labels = c("non-WUI", "WUI")) +
  scale_color_manual(values = c("#0072B2",   "#D55E00"),   labels = c("non-WUI", "WUI")) +
  labs(x = "", y = "Fire Density", title = "Total")
```
